modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
issueTrackerURL="https://github.com/Hashtag233/LightMeals/issues"
[[mods]]
modId="lightmeals"
version="2.1"
displayName="Light Meals"
updateJSONURL="https://gitlab.com/hashmod/services/-/raw/main/light-meals-upd.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/light-meals"
logoFile="light_meals_banner.png"
authors="Hashtag233, Ender_Ruier"
description="Add numerous foods within the vanilla system."
[[dependencies.lightmeals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.18.2]"
    ordering="NONE"
    side="BOTH"
